---
title: "ARA - Epiak"
output: 
  flexdashboard::flex_dashboard:
      orientation: columns
      vertical_layout: fill
      css: css/styles.css
      logo: img/logo.png
runtime: shiny
---

```{r setup, include=FALSE}
####### Loading R packages
library(shiny)
library(flexdashboard)
library(shinydashboard)
library(shinythemes)
library(shinyWidgets)
library(leaflet)
library(scales)
library(rgdal)
library(dplyr)
library(htmltools)
library(ggplot2)
library(RColorBrewer)
library(fmsb)
library(psych)
library(shapefiles)
library(ggradar)
library(ggcorrplot)
library(plotly)
library(DT)
library(sf)
library(odbc)
library(RSQLite)
library(yarrr)
library(reshape2)
library(tidyverse)
```

```{r}
Sys.setenv(SHAPE_RESTORE_SHX="YES")
```

```{r}
#Nesse chunk os dados vao ser coletados do banco de dados do cliente para serem
#usados para as visualizacoes e comparacoes

# Dados
# con <- dbConnect(RSQLite::SQLite(), )
# placeBase <- tbl(con, ) %>% collect()
# dbDisconnect(con)
placeBase <- read.csv("C:/Users/gsantiago/Documents/K-State/GeoComp-APP/Codes/Testing Shapefiles/KML/Condados.csv")

# KML
# cone <- dbConnect(RSQLite::SQLite(), )
# place <- tbl(cone, ) %>% collect()
# dbDisconnect(cone)
place <- readOGR("C:/Users/gsantiago/Documents/K-State/GeoComp-APP/Codes/Testing Shapefiles/KML/Condados.kml")

```

# Visualization

## Inputs {.sidebar data-width="350"}

```{r}
#Map
conditionalPanel(tags$style(type="text/css",
                 ".shiny-output-error { visibility: hidden; }",
                 ".shiny-output-error:before { visibility: hidden; }"),
                 condition = "input.tabselected==1",
                 uiOutput("select"),
                 uiOutput("yearmap"),
                 h6("Mean or sum of data between those years:"),
                 uiOutput("morsummap"))

list <- gsub("\\.", " ", names(subset(placeBase,select = -c(1,2))))

output$select <- renderUI({
  
    selectInput("select",
                   "Data you want to visualize on map:",
                   list)
  
  })
  
output$yearmap <- renderUI({
    
    year <- toString(names(subset(placeBase, select = c(2))))
    choice <- placeBase %>%
      group_by(Year = eval(parse(text = year)))
    minimo <- min(choice$Year)
    maximo <- max(choice$Year)
    sliderInput("yearmap",
                "Choose the mean between below years or one year:",
                min = minimo,
                max = maximo,
                value = c(minimo, maximo),
                step = 1,
                sep = "")
    
  })

output$morsummap <- renderUI({
  
  switchInput(
   inputId = "morsummap",
   value = TRUE,
   onLabel = "Mean",
   offLabel = "Sum",
   width = "400px",
   onStatus = "secondary")
  
})

```

```{r}
# Radar Chart

conditionalPanel(condition = "input.tabselected==2",
                uiOutput("placeoryearRadar"),
                uiOutput("selectplacesRadar"),
                uiOutput("yearRadar"),
                uiOutput("dataRadar"))
                
output$placeoryearRadar <- renderUI({
  
  selectInput("placeoryearRadar",
               h6("Compare different places in years or the same place in different years"),
               choices = c("Compare Places" = "MD",
                           "Compare Years" = "SD")
  )
  
})

output$selectplacesRadar <- renderUI({
  place <- toString(names(subset(placeBase, select = c(1))))
  choice <- placeBase %>%
    group_by(States = eval(parse(text = place)))
  
  if(input$placeoryearRadar == "MD"){
    
    selectizeInput("selectplacesRadar",
                   h6("Places you want to visualize on graph:"),
                   choices = c("Choose Places" = '',
                               choice$States),
                   multiple = TRUE)
  }
  
  else if(input$placeoryearRadar == "SD"){
    selectInput("selectplacesRadar",
                h6("Place you want to visualize on graph:"),
                choices = c("Choose a Place" = '',
                            choice$States))
  }
  
})

output$yearRadar <- renderUI({
  
  year <- toString(names(subset(placeBase, select = c(2))))
  choice <- placeBase %>%
    group_by(Year = eval(parse(text = year)))
  minimo <- min(choice$Year)
  maximo <- max(choice$Year)
  
  if(input$placeoryearRadar == "MD"){
    selectizeInput("yearRadar",
                   h6("Choose years you want to compare the mean values between them"),
                   choices = c("Choose years" = '',
                               choice$Year),
                   multiple = TRUE)
  }
  else if(input$placeoryearRadar == "SD"){
    selectizeInput("yearRadar",
                   h6("Choose years you want to compare"),
                   choices = c("Choose years" = '',
                               choice$Year),
                   multiple = TRUE)
  }
    
  
})

filterRadar <- reactive({
  
  place <- toString(names(subset(placeBase, select = c(1))))
  period <- toString(names(subset(placeBase, select = c(2))))
  
  placeBase %>%
    filter(eval(parse(text = place)) %in% input$selectplacesRadar,
           eval(parse(text = period)) %in% input$yearRadar) %>%
    select_if(~ !any(is.na(.)))
  
})

output$dataRadar <- renderUI({
  
  list <- gsub("\\.", " ", names(subset(filterRadar(), select = -c(1,2))))
  
  shinyWidgets::pickerInput(
    inputId = "dataRadar",
    label = h6("Select what data you want to visualize on radar plot:"),
    choices = list,
    multiple = TRUE)
  
})
```

```{r}

# Bar Filter

conditionalPanel(condition = "input.tabselected==3",
                uiOutput("placesBar"),
                uiOutput("yearBar"),
                h6("Mean or sum of data between those years:"),
                uiOutput("morsumbar"),
                uiOutput("stackBar"),
                uiOutput("dataBar")
              )

output$stackBar <- renderUI({
  
  selectInput("stackBar",
               h6("Do you want to stack you bar plot?"),
               choices = c("Yes" = "yes",
                           "No" = "no")
  )
  
})

output$placesBar <- renderUI({
    place <- toString(names(subset(placeBase, select = c(1))))
    choice <- placeBase %>%
      group_by(States = eval(parse(text = place)))
    
    selectizeInput("placesBar",
                   h6("Places you want to visualize on graph:"),
                   choices = c("Choose Places" = '',
                             choice$States),
                   multiple = TRUE)
    
  })
  
output$yearBar <- renderUI({
  
  year <- toString(names(subset(placeBase, select = c(2))))
  choice <- placeBase %>%
    group_by(Year = eval(parse(text = year)))
  minimo <- min(choice$Year)
  maximo <- max(choice$Year)
  
  sliderInput("yearBar",
              h6("Choose the years that will be ploted::"),
              min = minimo,
              max = maximo,
              value = c(minimo, maximo),
              step = 1,
              sep = "")
  
})

output$morsumbar <- renderUI({
  
  switchInput(
   inputId = "morsumbar",
   value = TRUE,
   onLabel = "Mean",
   offLabel = "Sum",
   onStatus = "secondary")
  
})

list <- gsub("\\.", " ", names(subset(placeBase,select = -c(1,2))))

output$dataBar <- renderUI({
  
  if(input$stackBar == "yes"){
    shinyWidgets::pickerInput(
    inputId = "dataBar",
    label = h6("Select what data you want to visualize on Bar plot:"),
    choices = list,
    multiple = TRUE
    )
  }
  else if(input$stackBar == "no"){
    shinyWidgets::pickerInput(
    inputId = "dataBar",
    label = h6("Select what data you want to visualize on Bar plot:"),
    choices = list
    )
  }
  
})

```

```{r}

# Box Filter

conditionalPanel(condition = "input.tabselected==6",
                uiOutput("placesBox"),
                uiOutput("yearBox"),
                uiOutput("dataBox")
              )

output$placesBox <- renderUI({
    place <- toString(names(subset(placeBase, select = c(1))))
    choice <- placeBase %>%
      group_by(States = eval(parse(text = place)))
    
    selectizeInput("placesBox",
                   h6("Places you want to visualize on graph:"),
                   choices = c("Choose Places" = '',
                             choice$States),
                   multiple = TRUE)
    
  })
  
output$yearBox <- renderUI({
  
  year <- toString(names(subset(placeBase, select = c(2))))
  choice <- placeBase %>%
    group_by(Year = eval(parse(text = year)))
  minimo <- min(choice$Year)
  maximo <- max(choice$Year)
  
  sliderInput("yearBox",
              h6("Choose the years that will be ploted::"),
              min = minimo,
              max = maximo,
              value = c(minimo, maximo),
              step = 1,
              sep = "")
  
})

list <- gsub("\\.", " ", names(subset(placeBase,select = -c(1,2))))

output$dataBox <- renderUI({
  
  shinyWidgets::pickerInput(
    inputId = "dataBox",
    label = h6("Select what data you want to visualize on Box plot:"),
    choices = list)
  
})

```

```{r}
# Correlation Filter

conditionalPanel(condition = "input.tabselected==4",
                uiOutput("placeCor"),
                uiOutput("yearCor"),
                uiOutput("dataCor")
              )

output$placeCor <- renderUI({
  
  place <- toString(names(subset(placeBase, select = c(1))))
  choice <- placeBase %>%
    group_by(States = eval(parse(text = place)))
  
  selectInput("placeCor",
              h6("Places you want to visualize on graph:"),
              choices = c("Choose one District" = '',
                          choice$States))
  
})

output$yearCor <- renderUI({
  
  year <- toString(names(subset(placeBase, select = c(2))))
  choice <- placeBase %>%
    group_by(Year = eval(parse(text = year)))
  
  selectizeInput("yearCor",
                   h6("Choose years below which you want to correlate"),
                   choices = c("Choose your years" = '',
                               choice$Year),
                   multiple = TRUE)
  
})

filterCor <- reactive({
  
  place <- toString(names(subset(placeBase, select = c(1))))
  period <- toString(names(subset(placeBase, select = c(2))))
  
  placeBase %>%
    filter(eval(parse(text = place)) %in% input$placeCor,
           eval(parse(text = period)) %in% input$yearCor) %>%
    select_if(~ !any(is.na(.)))
  
})

output$dataCor <- renderUI({
  
  list <- gsub("\\.", " ", names(subset(filterCor(),select = -c(1,2))))
  
  shinyWidgets::pickerInput(inputId = "dataCor",
                            label = h6("Select what data you want to correlate: "),
                            choices = list,
                            multiple = TRUE
        )
  
})

```

```{r}
# Line Filter

conditionalPanel(condition = "input.tabselected==5",
                 uiOutput("distOrVarLine"),
                uiOutput("placesLine"),
                uiOutput("yearLine"),
                uiOutput("dataLine")
              )

output$distOrVarLine <- renderUI({
  
  selectInput("distOrVarLine",
               h6("Compare between districts or between variables"),
               choices = c("Compare Districts" = "CDL",
                           "Compare Variables" = "CVL")
  )
  
})

output$placesLine <- renderUI({
    
  place <- toString(names(subset(placeBase, select = c(1))))
  choice <- placeBase %>%
    group_by(States = eval(parse(text = place)))
  
  if(input$distOrVarLine == "CDL"){
    selectizeInput("placesLine",
                 h6("Places you want to visualize on graph:"),
                 choices = c("Choose Districts" = '',
                             choice$States),
                 multiple = TRUE)
  }
  else if(input$distOrVarLine == "CVL"){
    selectInput("placesLine",
                 h6("Places you want to visualize on graph:"),
                 choices = c("Choose one district" = '',
                             choice$States))
  }
  
})
  
output$yearLine <- renderUI({
  
  year <- toString(names(subset(placeBase, select = c(2))))
  choice <- placeBase %>%
    group_by(Year = eval(parse(text = year)))
  minimo <- min(choice$Year)
  maximo <- max(choice$Year)
  
  sliderInput("yearLine",
              h6("Choose the years that will be ploted:"),
              min = minimo,
              max = maximo,
              value = c(minimo, maximo),
              step = 1,
              sep = "")
  
})

list <- gsub("\\.", " ", names(subset(placeBase,select = -c(1,2))))

output$dataLine <- renderUI({
  
  if(input$distOrVarLine == "CDL"){
    selectInput("dataLine",
                     h6("Select what data you want to visualize: "),
                     list)
  }
  else if(input$distOrVarLine == "CVL"){
    selectizeInput("dataLine",
                 h6("Select what data you want to visualize:"),
                 choices = c("Choose Variables" = '',
                             list),
                 multiple = TRUE)
  }

})

```

## Outputs {data-width="700"}

```{r}
tabsetPanel(type = "tabs",
            id = "tabselected",
            tabPanel(style = "margin: 15px",
                     "Map",
                     value=1,
                     leafletOutput("mymap",
                                  height = 600),
                      span(uiOutput("notavmap"),
                           style="text-align:center; font-weight: bold")
            ),
            tabPanel(style = "margin: 15px",
                     "Radar",
                     value=2,
                     plotlyOutput("graphRadar",
                                  height = 600)
            ),
            tabPanel(style = "margin: 15px",
                     "Correlation Chart",
                     value=4,
                     plotlyOutput("graphCor",
                                  height = 600)
            ),
            tabPanel(style = "margin: 15px",
                     "Line Chart",
                     value=5,
                     plotlyOutput("graphLine",
                                  height = 600)
            ),
            tabPanel(style = "margin: 15px",
                     "Bar Chart",
                     value=3,
                     plotlyOutput("graphBar",
                                  height = 600)
            ),
            tabPanel(style = "margin: 15px",
                     "Box Chart",
                     value=6,
                     plotlyOutput("graphBox",
                                  height = 600)
            )
          )
```

```{r}
####### Map Output

dataInput <- reactive({
  place <- toString(names(subset(placeBase, select = c(1))))
  period <- toString(names(subset(placeBase, select = c(2))))
  
  placeOrder <- unique(placeBase[,1])
  
  choice <- gsub("\\ ", ".", input$select)
  
  if(input$morsummap == TRUE){
    placeBase %>%
      filter(between(eval(parse(text = period)), input$yearmap[1], input$yearmap[2]))%>%
      group_by(Districts = eval(parse(text = place))) %>%
      summarise(Data = mean(eval(parse(text = choice)), na.rm=TRUE)) %>%
      arrange(factor(Districts, levels = placeOrder))
  }
  else if(input$morsummap == FALSE){
    placeBase %>%
      filter(between(eval(parse(text = period)), input$yearmap[1], input$yearmap[2]))%>%
      group_by(Districts = eval(parse(text = place))) %>%
      summarise(Data = sum(eval(parse(text = choice)), na.rm=TRUE)) %>%
      arrange(factor(Districts, levels = placeOrder))
  }
  
  
})

palette <- reactive({
  colorNumeric(c("#d7191c","#fdae61","#ffffbf","#abd9e9", "#2c7bb6"), domain = dataInput()$Data, reverse = TRUE)
})

pale <- reactive({
    colorNumeric(c("#d7191c","#fdae61","#ffffbf","#abd9e9", "#2c7bb6"), domain = dataInput()$Data)
})

labels <- reactive({
  
  titulo <- toString(input$select)
  
  paste("<p>", dataInput()$Districts, "<p>",
        "<p>", titulo, ": ", round(dataInput()$Data, digits = 2),"<p>",
        sep ="")
  
})

output$mymap <- renderLeaflet({
  
  titulo <- toString(input$select)
  
  if(input$poliorpoint == "PL"){
    if(!all(is.na(dataInput()$Data))){
      map <- leaflet(width = 200, height = 300) %>%
          addTiles() %>%
          addPolygons( data = place,
                       weight = 1,
                       smoothFactor = 0.5,
                       fillOpacity = 0.8,
                       color = ~pale()(dataInput()$Data),
                       highlight = highlightOptions(
                         weight = 5,
                         color = "#666666",
                         fillOpacity = 0.7,
                         bringToFront = TRUE
                       ),
                       label = lapply(labels(), HTML)
          ) %>%
          addLegend(pal = palette(),
                    values = dataInput()$Data,
                    opacity = 0.7,
                    position = "bottomright",
                    title = titulo,
                    na.label = "n/a", 
                    labFormat = labelFormat(transform = function(x) sort(x, decreasing = TRUE)))
      }
      else if(all(is.na(dataInput()$Data))){
        map <- leaflet(width = 200, height = 300) %>%
          addTiles() %>%
          addPolygons( data = place,
                       weight = 1,
                       smoothFactor = 0.5,
                       fillOpacity = 0.8,
                       color = "#808080",
                       highlight = highlightOptions(
                         weight = 5,
                         color = "#666666",
                         fillOpacity = 0.7,
                         bringToFront = TRUE
                       ),
                       label = lapply(labels(), HTML)
          )
      }
  }
  else if(input$poliorpoint == "PT"){
      if(!all(is.na(dataInput()$Data))){
        map <- leaflet(width = 200, height = 300) %>%
        addTiles() %>%
        addCircleMarkers( data = place(),
                          radius = 10,
                          color = "#9ba659",
                          label = lapply(labels(), HTML))
      }
     else if(all(is.na(dataInput()$Data))){
       map <- leaflet(width = 200, height = 300) %>%
        addTiles()
     }
  }
  
    map
})

output$notavmap <- renderText({
  
  if(all(is.na(dataInput()$Data))){
    "No data available on this year"
  }
  
  else if(any(is.na(dataInput()$Data))){
    "n/a = No Available"
  }
})
```

```{r}
# Radar Output

dataInputGraphRadar <- reactive({
  place <- toString(names(subset(placeBase, select = c(1))))
  period <- toString(names(subset(placeBase, select = c(2))))
  valores <- gsub("\\ ", ".", input$dataRadar)
  
  if(input$placeoryearRadar == "MD"){
    
    placeBase %>%
      filter(eval(parse(text = place)) %in% input$selectplacesRadar,
             eval(parse(text = period)) %in% input$yearRadar) %>%
      group_by(Places = eval(parse(text = place))) %>%
      summarise_at(vars(valores), mean, na.rm=TRUE) %>%
      ungroup() %>%
      mutate_at(vars(-Places), scales::rescale)
    
  }
  
  else if(input$placeoryearRadar == "SD"){
    
    placeBase %>%
      filter(eval(parse(text = place)) == input$selectplacesRadar,
             eval(parse(text = period)) %in% input$yearRadar) %>%
      group_by(Years = eval(parse(text = period))) %>%
      summarise_at(vars(valores), mean, na.rm=TRUE) %>%
      ungroup() %>%
      mutate_at(vars(-Years), scales::rescale)
    
  }
  
})

output$graphRadar <- renderPlotly({
  
  lista <- gsub("\\.", " ", colnames(dataInputGraphRadar())[-1])
  
  paleta <- brewer.pal(n = 8, name = "Spectral")
  paletaTransparente <- yarrr::transparent(paleta, .35)
  
  graph <- dataInputGraphRadar() %>%
      ggradar(
        font.radar = "roboto",
        grid.label.size = 4,
        axis.label.size = 4,
        group.point.size = 1.8,
        axis.labels = lista,
        group.colours = paletaTransparente
      ) + 
      theme(
        plot.background = element_rect(fill = "#f0f0f0"),
        panel.background = element_rect(fill = "#f0f0f0"),
        legend.position = "top",
        legend.justification = c(1, 0),
        legend.text = element_text(size = 8, family = "roboto"),
        legend.key = element_rect(fill = NA, color = NA),
        legend.background = element_blank()
      )
  
  ggplotly(graph, tooltip = "")
  
})

```

```{r}

# Bar Plot

dataInputBar <- reactive({
  place <- toString(names(subset(placeBase, select = c(1))))
  period <- toString(names(subset(placeBase, select = c(2))))
  
  choiceG <- gsub("\\ ", ".", input$dataBar)
  
  if(input$stackBar == "yes"){
    
    if(input$morsumbar == TRUE){
      placeBase %>%
        filter(eval(parse(text = place)) %in% input$placesBar,
               between(eval(parse(text = period)), input$yearBar[1], input$yearBar[2])) %>%
        group_by(Places = eval(parse(text = place))) %>%
        summarise_at(vars(choiceG), mean, na.rm=TRUE)%>%
        mutate_at(vars(choiceG), scales::rescale)
      
    }
    else if(input$morsumbar == FALSE){
      placeBase %>%
        filter(eval(parse(text = place)) %in% input$placesBar,
               between(eval(parse(text = period)), input$yearBar[1], input$yearBar[2])) %>%
        group_by(Places = eval(parse(text = place))) %>%
        summarise_at(vars(choiceG), sum, na.rm=TRUE) %>%
        mutate_at(vars(choiceG), scales::rescale)
      
    }
    
  }
  
  else if(input$stackBar == "no"){
    
    if(input$morsumbar == TRUE){
      placeBase %>%
        filter(eval(parse(text = place)) %in% input$placesBar,
               between(eval(parse(text = period)), input$yearBar[1], input$yearBar[2])) %>%
        group_by(Places = eval(parse(text = place))) %>%
        summarise(Data = mean(eval(parse(text = choiceG)), na.rm=TRUE))
      
    }
    else if(input$morsumbar == FALSE){
      placeBase %>%
        filter(eval(parse(text = place)) %in% input$placesBar,
               between(eval(parse(text = period)), input$yearBar[1], input$yearBar[2])) %>%
        group_by(Places = eval(parse(text = place))) %>%
        summarise(Data = sum(eval(parse(text = choiceG)), na.rm=TRUE))
      
    }
    
  }
  
  
})

output$graphBar <- renderPlotly({
  
  choiceD <- toString(input$dataBar)
  
  if(input$stackBar == "no"){
    
    legend <- paste(choiceD)
    
    barPlot <- ggplot(dataInputBar(), aes(x=Places, y=Data))+
                  geom_bar(stat="identity", color="#253659", fill="#285585")+
                  geom_text(aes(label=round(Data, 2)), vjust=1.6, color="#253659", size=4)+
                  theme(
                    panel.background = element_rect(fill = "#f0f0f0",
                                                    colour = "##f0f0f0",
                                                    size = 0.5, linetype = "solid"),
                    plot.background = element_rect(fill = "#dbd9d9"),
                    axis.title.y = element_text(size = 8)
                  )+
                  labs(y = legend)+
                  labs(x = "Places")+
                  scale_y_continuous(labels = comma)
    
    ggplotly(barPlot)
  }
  else if(input$stackBar == "yes"){
    
    legend <- paste(choiceD)
    
    data_long <- dataInputBar() %>%
      gather("Variables", "value", -c(Places))
    
    barPlot <- ggplot(data_long, aes(x=Places, y=value, group = Variables, fill=Variables))+
                  geom_col()+
                  theme(
                    panel.background = element_rect(fill = "#f0f0f0",
                                                    colour = "#f0f0f0",
                                                    size = 0.5, linetype = "solid"),
                    plot.background = element_rect(fill = "#f0f0f0"),
                    axis.title.y = element_text(size = 8)
                  )+
                  labs(y = legend)+
                  labs(x = "Districts")+
                  scale_y_continuous(labels = comma)
    
    ggplotly(barPlot)
  }
  
})

```

```{r}

# Box Plot

dataInputBox <- reactive({
  place <- toString(names(subset(placeBase, select = c(1))))
  period <- toString(names(subset(placeBase, select = c(2))))
  
  choiceG <- gsub("\\ ", ".", input$dataBox)
  
  placeBase %>%
    filter(eval(parse(text = place)) %in% input$placesBox,
           between(eval(parse(text = period)), input$yearBox[1], input$yearBox[2])) %>%
    group_by(Places = eval(parse(text = place)))%>%
    select(Data = as.name(choiceG))
  
  
})

output$graphBox <- renderPlotly({
  
  choiceD <- toString(input$dataBox)
  
  boxPlot <- ggplot(dataInputBox(), aes(x=Places, y=Data, color=Places))+
                geom_boxplot(notch=TRUE)+
                theme(
                  panel.background = element_rect(fill = "#f0f0f0",
                                                  colour = "#c7c7c9",
                                                  size = 0.5, linetype = "solid"),
                  plot.background = element_rect(fill = "#f0f0f0"),
                  axis.title.y = element_text(size = 8)
                )+
                labs(y = choiceD)+
        scale_y_continuous(labels = comma)
  
  ggplotly(boxPlot)
  
})


```

```{r}
# Correlation Output

dataInputCor <- reactive({
  
  
  
  place <- toString(names(subset(filterCor(), select = c(1))))
  period <- toString(names(subset(filterCor(), select = c(2))))
  choicesD <- gsub("\\ ", ".", input$dataCor)
  
  filterCor() %>%
    group_by(Places = eval(parse(text = place)))%>%
    select_at(vars(choicesD))
  
})

output$graphCor <- renderPlotly({
  
  corGraph <- dataInputCor()
  corGraph[,1] <- NULL
  colnames(corGraph) <- gsub("\\.", " ", colnames(corGraph))
  corr <- round(cor(corGraph), 1)
  
  corPlot <- ggcorrplot(corr,
                        hc.order = TRUE,
                        type = "lower",
                        lab = TRUE,
                        lab_size = 2,
                        show.diag = TRUE,
                        colors = c("red", "white","blue")) +
    theme(axis.text.x=element_text(size=9, angle=45, vjust=1, hjust=1, 
                                   margin=margin(-3,0,0,0)),
          axis.text.y=element_text(size=9),
          panel.grid.major=element_blank(),
          plot.background = element_rect(fill = "#f0f0f0"),
          panel.background = element_rect(fill = "#f0f0f0")) 
  
  ggplotly(corPlot)
  
})

```

```{r}
# Line Output

dataInputLine <- reactive({
    
  place <- toString(names(subset(placeBase, select = c(1))))
  period <- toString(names(subset(placeBase, select = c(2))))
  choicesD <- gsub("\\ ", ".", input$dataLine)
  
  if(input$distOrVarLine == "CDL"){
    
    placeBase %>%
      filter(eval(parse(text = place)) %in% input$placesLine,
             between(eval(parse(text = period)), input$yearLine[1], input$yearLine[2])) %>%
      group_by(Year = eval(parse(text = period)),
               Districts = eval(parse(text = place))) %>%
      select(Data = as.name(choicesD))
    
  }
  else if(input$distOrVarLine == "CVL"){
    
    placeBase %>%
      filter(eval(parse(text = place)) %in% input$placesLine,
             between(eval(parse(text = period)), input$yearLine[1], input$yearLine[2])) %>%
      select_at(vars(choicesD, period)) %>%
      rename(Year = period)%>%
      mutate_at(vars(choicesD), scales::rescale)
    
  }

})

output$graphLine <- renderPlotly({
  
  choiceD <- toString(input$dataLine)
  
  if(input$distOrVarLine == "CDL"){
    
    plotLine <- ggplot(dataInputLine(), aes(x = Year, y = Data, color = Districts)) +
    geom_line()+
    theme(panel.background = element_rect(fill = "#f0f0f0"),
          plot.background = element_rect(fill = "#f0f0f0"),
          axis.title.y = element_text(size = 8),
          legend.background = element_rect(fill = "#f0f0f0"))+
    labs(y = choiceD)+
    scale_x_continuous(breaks = dataInputLine()$Year)+
    scale_y_continuous(labels = comma)

  ggplotly(plotLine)
  
  }
  else if(input$distOrVarLine == "CVL"){
    
    data_long <- melt(dataInputLine(), id.vars="Year", variable.name = 'Variables')
    
    plotLine <- ggplot(data_long, aes(x = Year, y = value, colour = Variables)) +
    geom_line()+
    theme(panel.background = element_rect(fill = "#f0f0f0"),
          plot.background = element_rect(fill = "#f0f0f0"),
          axis.title.y = element_text(size = 8),
          legend.background = element_rect(fill = "#f0f0f0"))+
    labs(y = choiceD)+
    scale_x_continuous(breaks = dataInputLine()$Year)+
    scale_y_continuous(labels = comma)

  ggplotly(plotLine)
  
  }
  
})
```
